# Generated by Django 5.1.2 on 2024-10-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quize", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Викторина", "verbose_name_plural": "Викторины"},
        ),
        migrations.AlterModelOptions(
            name="quizchoice",
            options={
                "verbose_name": "Варианты ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.AlterModelOptions(
            name="quizquestion",
            options={"verbose_name": "Вопросы", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterModelOptions(
            name="quizresult",
            options={
                "verbose_name": "Результаты тестов",
                "verbose_name_plural": "Результаты тестов",
            },
        ),
        migrations.AlterModelOptions(
            name="quiztopic",
            options={"verbose_name": "Темы", "verbose_name_plural": "Темы"},
        ),
        migrations.AlterModelOptions(
            name="quiztype",
            options={
                "verbose_name": "Типы викторин",
                "verbose_name_plural": "Типы викторин",
            },
        ),
    ]
