# Generated by Django 5.1.2 on 2024-10-19 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_customuser_username"),
        ("quize", "0002_alter_quiz_options_alter_quizchoice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizchoice",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quize.quizquestion",
                verbose_name="Внешний ключ на quiz_question (вопрос)",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.image",
                verbose_name="Внешний ключ на таблицу image(изображение)",
            ),
        ),
    ]
