# Generated by Django 5.1.2 on 2024-10-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quize", "0003_alter_quizchoice_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizchoice",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="quize.quizquestion",
                verbose_name="Внешний ключ на quiz_question (вопрос)",
            ),
        ),
    ]
