# Generated by Django 5.1.2 on 2024-10-19 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_customuser_username"),
        ("quize", "0004_alter_quizchoice_question_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizchoice",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.image",
                verbose_name="Внешний ключ на quiz_image (изображение) — необязательное поле",
            ),
        ),
    ]
