# Generated by Django 5.1.2 on 2024-10-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="path",
            field=models.ImageField(upload_to="img"),
        ),
    ]
