# Generated by Django 5.1.2 on 2024-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
