# Generated by Django 5.1.2 on 2024-10-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название типа викторины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Типы викторин",
                "verbose_name_plural": "Типы викторин",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="activation_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city_or_village",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="language",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="school",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tg_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
