# Generated by Django 5.1.2 on 2024-10-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0008_quiztype_remove_customuser_activation_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="img",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_img",
                to="account.image",
                verbose_name="ава",
            ),
            preserve_default=False,
        ),
    ]
