# Generated by Django 5.1.2 on 2024-10-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_customuser_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="img",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_img",
                to="account.image",
                verbose_name="ава",
            ),
        ),
    ]
